spring:
  application:
    name: online-recruitment-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XXXXXXXXXXXXXXXXXXXXXXXXX
    url: jdbc:mysql://localhost:3306/db_recruitment?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      database: 0
      host: localhost
      password: XXXXXXXXXXXXXXXXXXXXXXXXX
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  secret: aofklasndflkasndkasherwlansldkgnflks6fas56f4a9sfasfhsjfhwi3435w3223423424
  expire-time: 259200000

# 阿里云OSS对象存储
oss:
  endpoint: XXXXXXXXXXXXXXXXXXXXXXXXX
  access-key-id: XXXXXXXXXXXXXXXXXXXXXXXXX
  access-key-secret: XXXXXXXXXXXXXXXXXXXXXXXXX
  bucket-name: XXXXXXXXXXXXXXXXXXXXXXXXX

#本地对象存储
minio:
  endpoint: XXXXXXXXXXXXXXXXXXXXXXXXX
  access-key: XXXXXXXXXXXXXXXXXXXXXXXXX
  secret-key: XXXXXXXXXXXXXXXXXXXXXXXXX
  bucket-name: XXXXXXXXXXXXXXXXXXXXXXXXX

#配置图片存储方式
recruitment:
  storage:
    type: aliyun #配置存储方式可选 aliyun、minio
